export const STYLE_BREAKPOINT_UPDATE = 'STYLE_BREAKPOINT_UPDATE';

export const ADD_POINT = 'ADD_POINT';
export const LABEL_CHANGED = 'LABEL_CHANGED';
export const CLEAR_POINTS = 'CLEAR_POINTS';
export const UNDO_POINTS = 'UNDO_POINTS';
export const REDO_POINTS = 'REDO_POINTS';
export const SET_ACTIVE_LABEL = 'SET_ACTIVE_LABEL';
export const SVC_ADD_POINT = 'SVC_ADD_POINT';
export const SVC_LABEL_CHANGED = 'SVC_LABEL_CHANGED';
export const SVC_CLEAR_POINTS = 'SVC_CLEAR_POINTS';
export const SVC_UNDO_POINT = 'SVC_UNDO_POINT';
export const SVC_REDO_POINT = 'SVC_REDO_POINT';
export const SVR_ADD_POINT = 'SVR_ADD_POINT';
export const SVR_CLEAR_POINTS = 'SVR_CLEAR_POINTS';
export const SVR_UNDO_POINT = 'SVR_UNDO_POINT';
export const SVR_REDO_POINT = 'SVR_REDO_POINT';
