export const STYLE_BREAKPOINT_UPDATE = 'STYLE_BREAKPOINT_UPDATE';
export const SVC_ADD_POINT = 'SVC_ADD_POINT';
export const SVC_LABEL_CHANGED = 'SVC_LABEL_CHANGED';
export const SVC_CLEAR_POINTS = 'SVC_CLEAR_POINTS';
export const SVC_UNDO_POINTS = 'SVC_UNDO_POINTS';
export const SVC_REDO_POINTS = 'SVC_UNDO_POINTS';